kind: pipeline
type: docker
name: client-build

# 仅当 client/ 目录或分支有变更时触发
trigger:
  branch:
    - main
  paths:
    include:
      - client/**
      - .drone.client.yml  # 自身配置变更也触发

steps:
  - name: build-upload-apk
    image: gradle:8.9
    volumes:
      - name: sdk
        path: /drone/src/client/sdk
      - name: gradle-cache
        path: /home/gradle/.gradle
    environment:
      ANDROID_HOME: /drone/src/sdk
    commands:
      - chmod +x gradlew
      - chmod +x updav
      - ./gradlew assembleRelease --stacktrace
      - APK_CLOUD=$(find "app/build/outputs/apk/cloud/release" -name "*.apk")
      - APK_LOCAL=$(find "app/build/outputs/apk/local/release" -name "*.apk")
      - ./updav -u http://192.168.8.6:8081 -a dev -p "Az*29!#^1Nan" -f "$APK_CLOUD","$APK_LOCAL" -r /ahao/heji/apk

volumes:
  - name: sdk
    host:
      path: /mnt/user/appdata/drone/tools/android/sdk
  - name: gradle-cache
    host:
      path: /mnt/user/appdata/drone/tools/gradle/cache-heji