app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8080'

options:
  db: mongo

mongo:
  host: 192.168.8.6
  port: 27017
  database: heji
  username: root
  password: Hao88.mongo!
  timeoutMax: 10s
minio:
  address: "192.168.8.6:9768"
  accessKey: "ELUGN04RII6WD4K59DEM"
  secretKey: "ObhJpLZ6dNvR1sw2ZOU8EgvFCC9yuzEZIqS+m+Ul"
  token: ""
redis:
  address: "192.168.8.6:6379"
  password:
  db:
jwt:
  secret: AV8DHao88.cloud1F@!9fe3=!W$W-FaF`L1L2I3I4E5W
  expirationTime: 720h


