// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.22.3
// source: message.proto

package wsmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型
type Type int32

const (
	Type_ADD_BILL            Type = 0
	Type_ADD_BILL_ACK        Type = 1
	Type_DELETE_BILL         Type = 2
	Type_DELETE_BILL_ACK     Type = 3
	Type_UPDATE_BILL         Type = 4
	Type_UPDATE_BILL_ACK     Type = 5
	Type_ADD_BOOK            Type = 6
	Type_ADD_BOOK_ACK        Type = 7
	Type_DELETE_BOOK         Type = 8
	Type_DELETE_BOOK_ACK     Type = 9
	Type_UPDATE_BOOK         Type = 10
	Type_UPDATE_BOOK_ACK     Type = 11
	Type_ADD_CATEGORY        Type = 12
	Type_ADD_CATEGORY_ACK    Type = 13
	Type_DELETE_GATEGORY     Type = 14
	Type_DELETE_GATEGORY_ACK Type = 15
	Type_UPDATE_GATEGORY     Type = 16
	Type_UPDATE_GATEGORY_ACK Type = 17
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "ADD_BILL",
		1:  "ADD_BILL_ACK",
		2:  "DELETE_BILL",
		3:  "DELETE_BILL_ACK",
		4:  "UPDATE_BILL",
		5:  "UPDATE_BILL_ACK",
		6:  "ADD_BOOK",
		7:  "ADD_BOOK_ACK",
		8:  "DELETE_BOOK",
		9:  "DELETE_BOOK_ACK",
		10: "UPDATE_BOOK",
		11: "UPDATE_BOOK_ACK",
		12: "ADD_CATEGORY",
		13: "ADD_CATEGORY_ACK",
		14: "DELETE_GATEGORY",
		15: "DELETE_GATEGORY_ACK",
		16: "UPDATE_GATEGORY",
		17: "UPDATE_GATEGORY_ACK",
	}
	Type_value = map[string]int32{
		"ADD_BILL":            0,
		"ADD_BILL_ACK":        1,
		"DELETE_BILL":         2,
		"DELETE_BILL_ACK":     3,
		"UPDATE_BILL":         4,
		"UPDATE_BILL_ACK":     5,
		"ADD_BOOK":            6,
		"ADD_BOOK_ACK":        7,
		"DELETE_BOOK":         8,
		"DELETE_BOOK_ACK":     9,
		"UPDATE_BOOK":         10,
		"UPDATE_BOOK_ACK":     11,
		"ADD_CATEGORY":        12,
		"ADD_CATEGORY_ACK":    13,
		"DELETE_GATEGORY":     14,
		"DELETE_GATEGORY_ACK": 15,
		"UPDATE_GATEGORY":     16,
		"UPDATE_GATEGORY_ACK": 17,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// 消息体
type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Type                   `protobuf:"varint,2,opt,name=type,proto3,enum=com.heji.proto.Type" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SenderId      string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverIds   []string               `protobuf:"bytes,5,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Packet) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_ADD_BILL
}

func (x *Packet) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Packet) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Packet) GetReceiverIds() []string {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *Packet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x0ecom.heji.proto\"\xba\x01\n" +
	"\x06Packet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.com.heji.proto.TypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12!\n" +
	"\freceiver_ids\x18\x05 \x03(\tR\vreceiverIds\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent*\xe2\x02\n" +
	"\x04Type\x12\f\n" +
	"\bADD_BILL\x10\x00\x12\x10\n" +
	"\fADD_BILL_ACK\x10\x01\x12\x0f\n" +
	"\vDELETE_BILL\x10\x02\x12\x13\n" +
	"\x0fDELETE_BILL_ACK\x10\x03\x12\x0f\n" +
	"\vUPDATE_BILL\x10\x04\x12\x13\n" +
	"\x0fUPDATE_BILL_ACK\x10\x05\x12\f\n" +
	"\bADD_BOOK\x10\x06\x12\x10\n" +
	"\fADD_BOOK_ACK\x10\a\x12\x0f\n" +
	"\vDELETE_BOOK\x10\b\x12\x13\n" +
	"\x0fDELETE_BOOK_ACK\x10\t\x12\x0f\n" +
	"\vUPDATE_BOOK\x10\n" +
	"\x12\x13\n" +
	"\x0fUPDATE_BOOK_ACK\x10\v\x12\x10\n" +
	"\fADD_CATEGORY\x10\f\x12\x14\n" +
	"\x10ADD_CATEGORY_ACK\x10\r\x12\x13\n" +
	"\x0fDELETE_GATEGORY\x10\x0e\x12\x17\n" +
	"\x13DELETE_GATEGORY_ACK\x10\x0f\x12\x13\n" +
	"\x0fUPDATE_GATEGORY\x10\x10\x12\x17\n" +
	"\x13UPDATE_GATEGORY_ACK\x10\x11B\x1e\n" +
	"\x12com.hao.heji.protoZ\b../wsmsgb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(Type)(0),      // 0: com.heji.proto.Type
	(*Packet)(nil), // 1: com.heji.proto.Packet
}
var file_message_proto_depIdxs = []int32{
	0, // 0: com.heji.proto.Packet.type:type_name -> com.heji.proto.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
